---
- name: "Including OS-specific or default variables for global packages"
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.codename }}.yml"
    - "packages.yml"

- name: "Installing global APT packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: true
    packages: "{{ apt_packages }}"

- name: "Setting up XClip"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/xclip"

- name: "Setting up Google Chrome"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/google-chrome"

- name: "Setting up VSCode"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/vscode"

- name: "Setting up HashiCorp packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/hashicorp"

- name: "Setting up the Docker"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/docker"

- name: "Setting up XRDP"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/xrdp"

- name: "Setting up VirtualBox"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/virtualbox"
  vars:
    user: "{{ lookup('env', 'USER') }}"
